### ISSUE TITLE
Publish artifact to maven central

### ISSUE THREAD

**Issue by cforce** [sachin-handiekar/spring-social-live#6]

**Comment by sachin-handiekar** [comment]
I don't have access to Spring Central repo. Most of the spring-social community projects are not available in Maven Central. 

The only way I can get them available is to change the groupId from org.springframework.social to com.sachinhandiekar.social

**Comment by cforce** [comment]
If spring does not want to provide space on their repo for community project they advetising on their official spring soical hp thats sad.
Providing easy access to artifacts (for people who don't want to download and install every all of dependencies) its important, so name it how ever you need to bring it online on maven depedency managment. I would be glad to see someone from spring who will argue, why not have a spring social community process to file such artifacts in a common manner (group/artifact guidlines an repo location)

**Comment by raulgd** [comment]
I know this was asked quite a while ago, but I see it's open.

There are other community projects that instead of changing the groupId, they use something like bintray and create their own repositories to distribute them.

So you just add the project's repository URL to your build configuration and get the dependency.

Bintray is free for public repositories, it's only when using private repos that you have to pay for the service.

**Comment by sachin-handiekar** [comment]
@raulgd Thnks for the suggestion. Will try to integrate with Bintray on this weekend.

**Comment by cforce** [comment]
Can't  find any on https://bintray.com/sachin/spring-social-live/spring-social-live

**Comment by sachin-handiekar** [comment]
Available on Maven Central - https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-social-live%22
